name: Windows Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    # Permette di far partire la build manualmente

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.41.5"

      - name: Get dependencies
        run: flutter pub get

      - name: Enable Windows support
        run: flutter config --enable-windows-desktop

      - name: Build Windows
        run: flutter build windows --release

      - name: Copy Visual C++ Redistributable DLLs
        run: |
          copy "C:\Windows\System32\msvcp140.dll" "build\windows\x64\runner\Release\"
          copy "C:\Windows\System32\vcruntime140.dll" "build\windows\x64\runner\Release\"
          copy "C:\Windows\System32\vcruntime140_1.dll" "build\windows\x64\runner\Release\"
        shell: cmd

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-portable
          path: build/windows/x64/runner/Release/
